/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.UserRole;

import Business.Account.Account;
import Business.Account.Account.AccountStatus;
import Business.Business;
import Business.Enterprise.Government;
import Business.Network.Network;
import Business.Organization.InventoryOrganization;
import Business.Organization.Organization;
import Business.Person.BenefitPerson;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Chance
 */
public class UserWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form UserWorkArea
     */
    private JPanel userProcessContainer;
    private Business business;
    private Network network = null;
    private Account account;
    private BenefitPerson benefitperson;
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public UserWorkArea(JPanel userProcessContainer, Account account,  Business business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        this.benefitperson = (BenefitPerson)account.getPerson();
        for(Network nwk: this.business.getNetworkList()) {
            if(nwk.getState() == benefitperson.getState()) {
                this.network = nwk;
                break;
            }
        }
        System.out.println(this.network);
        
        this.showStatus();
    }
    
    public void showStatus() {
        if(this.account != null) {
            this.labelStatus.setText(this.account.getStatus().getValue());
        }
        if(this.account.getStatus() == AccountStatus.Registered) {
            this.btnApplyPlan.setEnabled(true);
            this.btnCheckPlan.setEnabled(false);
            this.btnActivate.setEnabled(false);
            this.btnHistory.setEnabled(false);
        }
        if(this.account.getStatus() == AccountStatus.Processing) {
            this.btnApplyPlan.setEnabled(false);
            this.btnCheckPlan.setEnabled(false);
            this.btnActivate.setEnabled(false);
            this.btnHistory.setEnabled(false);
        }
        if(this.account.getStatus() == AccountStatus.Approved) {
            this.btnApplyPlan.setEnabled(false);
            this.btnCheckPlan.setEnabled(false);
            this.btnActivate.setEnabled(true);
            this.btnHistory.setEnabled(false);
        }
        if(this.account.getStatus() == AccountStatus.Denied) {
            this.btnApplyPlan.setEnabled(true);
            this.btnCheckPlan.setEnabled(false);
            this.btnActivate.setEnabled(false);
            this.btnHistory.setEnabled(false);
        }
        if(this.account.getStatus() == AccountStatus.Activate) {
            this.btnApplyPlan.setEnabled(false);
            this.btnActivate.setEnabled(false);
            this.btnCheckPlan.setEnabled(true);
            this.btnHistory.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnApplyPlan = new javax.swing.JButton();
        labelStatus = new javax.swing.JLabel();
        btnCheckPlan = new javax.swing.JButton();
        btnActivate = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Personal Information");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Account Status:");

        btnApplyPlan.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnApplyPlan.setText("Apply a plan");
        btnApplyPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyPlanActionPerformed(evt);
            }
        });

        labelStatus.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        btnCheckPlan.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnCheckPlan.setText("Check My Plan");
        btnCheckPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckPlanActionPerformed(evt);
            }
        });

        btnActivate.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnActivate.setText("Activate Account");
        btnActivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivateActionPerformed(evt);
            }
        });

        btnHistory.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnHistory.setText("Benefit History");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnActivate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnApplyPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnActivate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCheckPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyPlanActionPerformed
        JPanel planApplyJPanel = new PlanApplyJPanel(userProcessContainer, this.business, this.network, this.account);
        userProcessContainer.add("planApplyJPanel", planApplyJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnApplyPlanActionPerformed

    private void btnCheckPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckPlanActionPerformed
        CheckMyPlanJPanel checkMyPlanJPanel = new CheckMyPlanJPanel(userProcessContainer, this.business, this.network, this.account);
        userProcessContainer.add("checkMyPlanJPanel", checkMyPlanJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCheckPlanActionPerformed

    private void btnActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivateActionPerformed
        this.account.setStatus(AccountStatus.Activate);
        this.showStatus();
    }//GEN-LAST:event_btnActivateActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        OrderHistoryJPanel orderHistoryJPanel = new OrderHistoryJPanel(userProcessContainer, this.business, this.network, this.account);
        userProcessContainer.add("orderHistoryJPanel", orderHistoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivate;
    private javax.swing.JButton btnApplyPlan;
    private javax.swing.JButton btnCheckPlan;
    private javax.swing.JButton btnHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelStatus;
    // End of variables declaration//GEN-END:variables
}
