/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Monitor;

import Business.Account.Account;
import Business.Business;
import Business.Network.Network;
import Business.Organization.InventoryOrganization;
import Business.Organization.Organization;
import Business.Person.BenefitPerson;
import Business.Plan.Plan;
import java.awt.CardLayout;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Chance
 */
public class MonitorPlan extends javax.swing.JPanel {

    /**
     * Creates new form Plan
     */
    private JPanel userProcessContainer;
    private Business business;
    private Account account;
    private InventoryOrganization organization;
    private Network network;
    public MonitorPlan(JPanel userProcessContainer, Account account, Organization organization, Network network, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        this.network = network;
        
        final DefaultCategoryDataset  dataset = new DefaultCategoryDataset ();  
        for(Plan plan: network.getGovernment().getPlanlist().getPlanList()) {
            int count = 0;
            final String name = plan.toString();
            for (Account ac : network.getGovernment().getAccountDirectory().getAccountCatalog()) {
                if (ac.getPerson() instanceof BenefitPerson) {
                    if (ac.getStatus() == Account.AccountStatus.Approved || ac.getStatus() == Account.AccountStatus.Activate) {
                        BenefitPerson bp = (BenefitPerson) ac.getPerson();
                        if (bp.getPlanAssign() == plan) {
                            count += 1;
                        }
                    }
                }
            }
            dataset.addValue(count, name, network.getState());
        }
        JFreeChart chart = ChartFactory.createBarChart(
            "Plan Monitor", // chart title
            "States", // domain axis label
            "Assigned Person", // range axis label
            dataset, // data
            PlotOrientation.VERTICAL, // orientation
            true, // include legend
            true, // tooltips?
            false // URLs?
        );
        ChartPanel chartPanel = new ChartPanel(chart, false);
        this.add("chartPanel", chartPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
