/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Monitor;

import Business.Account.Account;
import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FoodBank;
import Business.Food.FoodInventory;
import Business.Network.Network;
import Business.Organization.InventoryOrganization;
import Business.Organization.Organization;
import Business.Request.FoodRequest;
import Business.Request.Request;
import Business.Request.Request.RequestType;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Chance
 */
public class MonitorTransfer extends javax.swing.JPanel {

    /**
     * Creates new form MonitorTransfer
     */
    private JPanel userProcessContainer;
    private Business business;
    private Account account;
    private InventoryOrganization organization;
    private Network network;
    
    public MonitorTransfer(JPanel userProcessContainer, Account account, Organization organization, Network network, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        this.network = network;
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for(Request req : this.business.getFoodTransRequestList().getRequestList()) {
            FoodRequest foodReq = (FoodRequest) req;
            dataset.addValue(foodReq.getQuantity(), foodReq.getFood().toString(), foodReq.getEnterprise().toString());
        }
        
        JFreeChart chart = ChartFactory.createBarChart(
            "Transfer Monitor", // chart title
            "transfer", // domain axis label
            "Quantity", // range axis label
            dataset, // data
            PlotOrientation.VERTICAL, // orientation
            true, // include legend
            true, // tooltips?
            false // URLs?
        );
        ChartPanel chartPanel = new ChartPanel(chart, false);
        this.add("chartPanel", chartPanel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
