/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Account.Account;
import Business.Business;
import Business.Network.Network;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Enterprise.FoodBank;
import Business.Enterprise.Agent;
import Business.ConfigureASystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Supplier;
import Business.Organization.Organization;
import Interface.SupplierRole.SupplierRegisterJPanel;
import Interface.UserRole.UserRegisterJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Chance
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Business business;
    private DB4OUtil db4oUtil = DB4OUtil.getInstance();
    public MainJFrame() {
        initComponents();
        //this.business = ConfigureASystem.configure();
        this.business = db4oUtil.retrieveSystem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        loginJButton = new javax.swing.JButton();
        logoutJButton = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnRegistersup = new javax.swing.JButton();
        workareaJpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 400));
        setPreferredSize(new java.awt.Dimension(750, 420));

        jSplitPane1.setDividerLocation(140);

        jLabel1.setText("User Name");

        jLabel2.setText("Password");

        loginJButton.setText("Login");
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });

        logoutJButton.setText("Logout");
        logoutJButton.setEnabled(false);
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });

        btnRegister.setBackground(new java.awt.Color(204, 255, 204));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnRegistersup.setBackground(new java.awt.Color(204, 255, 204));
        btnRegistersup.setText("Register Supplier");
        btnRegistersup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistersupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUserName)
                    .addComponent(btnRegistersup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnRegister, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginJButton)
                .addGap(18, 18, 18)
                .addComponent(logoutJButton)
                .addGap(18, 18, 18)
                .addComponent(btnRegister)
                .addGap(18, 18, 18)
                .addComponent(btnRegistersup)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        workareaJpanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(workareaJpanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        // Get user name
        String userName = txtUserName.getText();
        // Get Password
        String password = String.valueOf(txtPassword.getPassword());
        if(userName.equals("") || password.equals("")){
            JOptionPane.showMessageDialog(null, "Invalid Credentails!");
            return;
        }
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        Account loginacc = this.business.getAccountDirectory().authenticateUser(userName, password);
        if(loginacc == null) {
            JOptionPane.showMessageDialog(null, "inValid Account. Please try agagin.");
            return ;
        }
        Account workareaAcc = null;
        //Network
        for(Network network : this.business.getNetworkList()) {
            workareaAcc = network.getGovernment().getAccountDirectory().authenticateUser(userName, password);
            if(workareaAcc != null) {
                break;
            } else {
                //FoodBank & Supplier
                for(Enterprise enterprise: network.getGovernment().getEnterpriseDirectory().getEnterpriseDirectory()) {
                    workareaAcc = enterprise.getAccountDirectory().authenticateUser(userName, password);
                    if(workareaAcc == null) {
                        if(enterprise.getType() == EnterpriseType.FoodBank) {
                            FoodBank foodbank = (FoodBank)enterprise;
                            for(Organization foodbankorg: foodbank.getOdir().getOrgDir()) {
                                workareaAcc = foodbankorg.getAccountDirectory().authenticateUser(userName, password);
                                if(workareaAcc != null) {
                                    inOrganization = foodbankorg;
                                    inEnterprise = enterprise;
                                    break;
                                }
                            }
                            for(Enterprise subEnterprise: foodbank.getEdir().getEnterpriseDirectory()) {
                                workareaAcc = subEnterprise.getAccountDirectory().authenticateUser(userName, password);
                                if(workareaAcc == null) {
                                    Agent agent = (Agent)subEnterprise;
                                    for(Organization org: agent.getOdir().getOrgDir()) {
                                        workareaAcc = org.getAccountDirectory().authenticateUser(userName, password);
                                        if(workareaAcc == null) {
                                        } else {
                                            inOrganization = org;
                                            inEnterprise = subEnterprise;
                                        }
                                    }
                                } else {
                                    inEnterprise = subEnterprise;
                                }
                            }
                        }
                        if(enterprise.getType() == EnterpriseType.Supplier) {
                            Supplier supplier = (Supplier)enterprise;
                            for(Organization org: supplier.getOdir().getOrgDir()) {
                                workareaAcc = org.getAccountDirectory().authenticateUser(userName, password);
                                if(workareaAcc == null) {
                                } else {
                                    inOrganization = org;
                                    inEnterprise = enterprise;
                                    break;
                                }
                            }
                        }
                    } else {
                        inEnterprise = enterprise;
                    }
                }
            }
        }
        //System.out.println("inEnter:"+inEnterprise);
        CardLayout layout = (CardLayout)workareaJpanel.getLayout();
        this.workareaJpanel.add("workArea", loginacc.getAccountRole().createWorkArea(workareaJpanel, loginacc, inOrganization, inEnterprise, business));
        layout.next(workareaJpanel);
        
        loginJButton.setEnabled(false);
        logoutJButton.setEnabled(true);
        txtUserName.setEnabled(false);
        txtPassword.setEnabled(false);
        btnRegister.setEnabled(false);
        btnRegistersup.setEnabled(false);
    }//GEN-LAST:event_loginJButtonActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        logoutJButton.setEnabled(false);
        txtUserName.setEnabled(true);
        txtPassword.setEnabled(true);
        loginJButton.setEnabled(true);
        btnRegister.setEnabled(true);
        btnRegistersup.setEnabled(true);

        txtUserName.setText("");
        txtPassword.setText("");

        workareaJpanel.removeAll();
        JPanel blankJP = new JPanel();
        workareaJpanel.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) workareaJpanel.getLayout();
        crdLyt.next(workareaJpanel);
        
        db4oUtil.storeSystem(business);
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        JPanel registerJPanel = new UserRegisterJPanel(workareaJpanel, this.business);
        workareaJpanel.add("registerJPanel", registerJPanel);
        CardLayout crdLyt = (CardLayout) workareaJpanel.getLayout();
        crdLyt.next(workareaJpanel);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnRegistersupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistersupActionPerformed
        JPanel registersJPanel = new SupplierRegisterJPanel(workareaJpanel, this.business);
        workareaJpanel.add("rsupplierJPanel", registersJPanel);
        CardLayout crdLyt = (CardLayout) workareaJpanel.getLayout();
        crdLyt.next(workareaJpanel);
    }//GEN-LAST:event_btnRegistersupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegistersup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginJButton;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPanel workareaJpanel;
    // End of variables declaration//GEN-END:variables
}
