/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageCustomers;

import Business.FlSchedule;
import Business.Flight;
import Business.MsSchedule;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author zhaoxiaohan
 */
public class FlightsFoundJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FlightsFoundJPanel
     */
    private JPanel CardSequenceJPanel;
    private TravelAgency travelAgency;
    private FlSchedule flschedule;
   
    public FlightsFoundJPanel(JPanel CardSequenceJPanel,TravelAgency travelAgency) {
    	
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.travelAgency = travelAgency;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgPre = new javax.swing.ButtonGroup();
        txtTakeOffDate = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtTakeOffAirport = new javax.swing.JTextField();
        txtArrivalAirport = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbMor = new javax.swing.JRadioButton();
        rbDay = new javax.swing.JRadioButton();
        rbEve = new javax.swing.JRadioButton();

        txtTakeOffDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jLabel5.setText("Preferred time of day: ");

        btnBack.setText("<back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setText("take off airport:");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel3.setText("Arrival airport:");

        jLabel6.setText("Find your best flight");

        jLabel4.setText("Take off date:");

        btgPre.add(rbMor);
        rbMor.setText("morning");
        rbMor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMorActionPerformed(evt);
            }
        });

        btgPre.add(rbDay);
        rbDay.setText("day time");

        btgPre.add(rbEve);
        rbEve.setText("evening ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbMor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbDay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbEve))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTakeOffDate, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(txtTakeOffAirport, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(txtArrivalAirport)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnSearch))
                    .addComponent(jLabel6))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(btnBack))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTakeOffAirport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbMor)
                                .addComponent(rbDay)
                                .addComponent(rbEve)))
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtArrivalAirport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTakeOffDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.previous(CardSequenceJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    	MsSchedule msschedule = new MsSchedule();//每次搜索前重置搜索结果
    	
        String takeoffairport = txtTakeOffAirport.getText();
        String arrivalairport = txtArrivalAirport.getText();
        String takeoffdate = txtTakeOffDate.getText();
        
        try{
            Date dateTime = new Date();
            SimpleDateFormat d1 = new SimpleDateFormat("yyyy-MM-dd");
            dateTime = d1.parse(takeoffdate);
        }
        catch(ParseException e){
            JOptionPane.showMessageDialog(null, "date format:yyyy-MM-dd");
            return;
        }
        
        if("".equals(takeoffairport)){
        	JOptionPane.showMessageDialog(null, "Please input a takeoffairport!");
            return;
        }
        if("".equals(arrivalairport)){
        	JOptionPane.showMessageDialog(null, "Please input a arrivalairport!");
            return;
        }
        if(!rbMor.isSelected()&&!rbDay.isSelected()&&!rbEve.isSelected()){
        	JOptionPane.showMessageDialog(null, "Please check a preferred time of day!!");
            return;
        }
        
        for(Flight flight: travelAgency.getMsschedule().getMsschedule())
        {
            if(flight.getTakeoffairport().equals(takeoffairport)&&flight.getArriveairport().equals(arrivalairport)&&flight.getTakeoffdate().equals(takeoffdate)){
            	int hour = Integer.parseInt(flight.getTakeofftime().split(":")[0]);
            	if((rbMor.isSelected()&&hour<=9)||(rbDay.isSelected()&&hour>9&&hour<=17)||(rbEve.isSelected()&&hour>17)){
            		msschedule.addFlights(flight);	
            	}
            }	
        }
        FlightDetailJPanel panel = new FlightDetailJPanel(CardSequenceJPanel,msschedule);
        CardSequenceJPanel.add("FlightDetailJPanel",panel);
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void rbMorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgPre;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rbDay;
    private javax.swing.JRadioButton rbEve;
    private javax.swing.JRadioButton rbMor;
    private javax.swing.JTextField txtArrivalAirport;
    private javax.swing.JTextField txtTakeOffAirport;
    private javax.swing.JFormattedTextField txtTakeOffDate;
    // End of variables declaration//GEN-END:variables
}
