/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SystemAdmin;

import Business.Account.Account;
import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 * @author Chance
 */
public class SystemAdminWorkArea extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Account account;
    private Organization organization;
    private Enterprise enterprise;
    private Business business;
    public SystemAdminWorkArea(JPanel userProcessContainer, Account account, 
                                    Organization organization, Enterprise enterprise, Business system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = system;
        //this.populateTree();
        this.init();
    }
    
    public void init() {
        ManageNetworkJPanel manageNetWorkJPanel = new ManageNetworkJPanel(sysTabbedPane, business);
        sysTabbedPane.addTab("NetWork", null, manageNetWorkJPanel, "ManageNetWork");
        /**
        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(sysTabbedPane, business);
        sysTabbedPane.addTab("Enterprise", null, manageEnterpriseJPanel,"ManageEnterprise");
        
        ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel = new ManageEnterpriseAdminJPanel(sysTabbedPane, business);
        sysTabbedPane.addTab("Enterprise Admin", null, manageEnterpriseAdminJPanel,"Enterprise Admin");
        * */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sysTabbedPane = new javax.swing.JTabbedPane();

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("System Admin Work Area");

        sysTabbedPane.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(347, Short.MAX_VALUE))
            .addComponent(sysTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sysTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane sysTabbedPane;
    // End of variables declaration//GEN-END:variables
}
