/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.InventoryRole;

import Business.Account.Account;
import Business.Business;
import Business.Enterprise.Agent;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Enterprise.FoodBank;
import Business.Enterprise.Government;
import Business.Enterprise.Supplier;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Chance
 */
public class InventoryWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InventoryWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Business business;
    private Account account;
    private Enterprise enterprise;
    private Government government = null;
    private Network network = null;
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public InventoryWorkAreaJPanel(JPanel userProcessContainer, Account account, Enterprise enterprise, Business business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        this.enterprise = enterprise;
        System.out.println("Enterprise:"+this.enterprise);
        //System.out.println(enterprise.getType());
        btnTransfer.setEnabled(false);
        if (enterprise instanceof Agent) {
            btnIn.setEnabled(true);
            btnOut.setEnabled(false);
            for(Network nw : this.business.getNetworkList()) {
                for(Enterprise tempenterp: nw.getGovernment().getEnterpriseDirectory().getEnterpriseDirectory()) {
                    if(tempenterp.getType() == EnterpriseType.FoodBank) {
                        FoodBank fb = (FoodBank)tempenterp;
                        for(Enterprise subenterprise: fb.getEdir().getEnterpriseDirectory()) {
                            if(enterprise == subenterprise) {
                                this.government = nw.getGovernment();
                                this.network = nw;
                            }
                        }
                    }
                }
            }
        }
        if (enterprise instanceof FoodBank) {
            btnIn.setEnabled(true);
            btnOut.setEnabled(true);
            btnTransfer.setEnabled(true);
            System.out.println("Business:"+this.business);
            for(Network nw : this.business.getNetworkList()) {
                for(Enterprise etp: nw.getGovernment().getEnterpriseDirectory().getEnterpriseDirectory()) {
                    if(this.enterprise == etp) {
                        this.government = nw.getGovernment();
                        this.network = nw;
                    }
                    //System.out.println("Checking enterprise:"+etp.hashCode());
                    //System.out.println("Enterprise Input:"+this.enterprise.hashCode());
                }
            }
        }
        if (enterprise instanceof Supplier) {
            btnIn.setEnabled(true);
            btnOut.setEnabled(true);
            for(Network nw : this.business.getNetworkList()) {
                for(Enterprise etp: nw.getGovernment().getEnterpriseDirectory().getEnterpriseDirectory()) {
                    if(enterprise == etp) {
                        this.government = nw.getGovernment();
                        this.network = nw;
                    }
                }
            }
        }
        System.out.println("Government:"+ this.network.getState());
        System.out.println("Government Hash from workarea:"+this.government.hashCode());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOut = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();
        btnTransfer = new javax.swing.JButton();

        btnOut.setText("Stock - Out");
        btnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutActionPerformed(evt);
            }
        });

        btnIn.setText("Stock - In");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        btnTransfer.setText("Transfer");
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(btnIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOut, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                .addContainerGap(344, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btnOut, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutActionPerformed
        // TODO add your handling code here:
        OutputInventoryJPanel outputInventoryJPanel = new OutputInventoryJPanel(userProcessContainer, business,account, enterprise, government);
        userProcessContainer.add("outputInventoryJPanel", outputInventoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOutActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        // TODO add your handling code here:
        InputInventoryJPanel inputInventoryJPanel = new InputInventoryJPanel(userProcessContainer,enterprise,account,government,business);
        userProcessContainer.add("inputInventoryJPanel", inputInventoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnInActionPerformed

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
        // TODO add your handling code here:
        TransferJPanel transferJPanel = new TransferJPanel(userProcessContainer,enterprise,account, government, business);
        userProcessContainer.add("transferJPanel", transferJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnTransferActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnOut;
    private javax.swing.JButton btnTransfer;
    // End of variables declaration//GEN-END:variables
}
