/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.InventoryRole;

import Business.Account.Account;
import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FoodBank;
import Business.Enterprise.Government;
import Business.Food.FoodInventory;
import Business.Request.FoodRequest;
import Business.Request.Request;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zhaoxiaohan
 */
public class TransferJPanel extends javax.swing.JPanel {

    /**
     * Creates new form transferJPanel
     */
    private JPanel userProcessContainer;
    private FoodBank foodBank;
    private Account account;
    private Business business;
    private Government government;

    public TransferJPanel(JPanel userProcessContainer, Enterprise enterprise, Account account, Government government, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        this.foodBank = (FoodBank) enterprise;
        this.government = government;
        populateFoodBankInventoryTable();
        populateFoodBankTransferRequestTable();

        this.workRequestJTable.getSelectionModel().addListSelectionListener(
                new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                // do some actions here, for example
                if (workRequestJTable.getSelectedRow() > -1) {
                    tableListener();
                }
            }
        });
    }

    public void populateFoodBankInventoryTable() {
        DefaultTableModel model = (DefaultTableModel) tblin.getModel();

        model.setRowCount(0);
        for (FoodInventory inventory : foodBank.getInventoryList()) {
            Object[] row = new Object[3];
            row[0] = inventory;
            row[1] = inventory.getFood().getPrice();
            row[2] = inventory.getQuantity();

            model.addRow(row);
        }
    }

    public void populateFoodBankTransferRequestTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);
        for (Request request : business.getFoodTransRequestList().getRequestList()) {
            FoodRequest foodRequest = (FoodRequest) request;
            Object[] row = new Object[7];
            row[0] = foodRequest;
            row[1] = foodRequest.getFood().getName();
            row[2] = foodRequest.getQuantity();
            row[3] = foodRequest.getEnterprise();
            row[4] = foodRequest.getReceiver();
            row[5] = foodRequest.getStatus();
            String shipping = foodRequest.getShipping();
            row[6] = shipping == null ? "Waiting" : shipping;

            model.addRow(row);
        }
    }

    public void tableListener() {
        FoodRequest foodRequest = (FoodRequest) workRequestJTable.getValueAt(workRequestJTable.getSelectedRow(), 0);
        if (foodRequest.getSender() == this.account) {
            this.btnAssign.setEnabled(false);
            if (foodRequest.getStatus().equals("Shipping")) {
                this.btnReceive.setEnabled(true);
                this.btnShipping.setEnabled(false);
            } else {
                this.btnReceive.setEnabled(false);
                this.btnShipping.setEnabled(false);
            }
        } else {
            this.btnReceive.setEnabled(false);
            if (foodRequest.getStatus().equals("Sent")) {
                this.btnAssign.setEnabled(true);
                this.btnShipping.setEnabled(false);
            } else if (foodRequest.getStatus().equals("Pending")) {
                if (foodRequest.getReceiver() == this.account) {
                    this.btnShipping.setEnabled(true);
                    this.btnAssign.setEnabled(false);
                } else {
                    this.btnShipping.setEnabled(false);
                    this.btnAssign.setEnabled(false);
                }
            } else {
                this.btnShipping.setEnabled(false);
                this.btnAssign.setEnabled(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblin = new javax.swing.JTable();
        btnRequest = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();
        btnReceive = new javax.swing.JButton();
        btnShipping = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setText("FoodBank Transfer");

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "FoodName", "Quantity", "Enterprise", "Receiver", "Status", "Shipping message"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                workRequestJTablePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        tblin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Food name", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblin);

        btnRequest.setText("request transfer");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        btnAssign.setText("assign to me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnReceive.setText("receive transfer");
        btnReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiveActionPerformed(evt);
            }
        });

        btnShipping.setText("send shipping msg");
        btnShipping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShippingActionPerformed(evt);
            }
        });

        btnBack.setText("<back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReceive, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(18, 18, 18)
                                .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnShipping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAssign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRequest)
                    .addComponent(btnAssign)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShipping)
                    .addComponent(btnReceive))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        //System.out.println("Government Hash from Transfer JPanel:"+this.government.hashCode());
        userProcessContainer.add("RequestOrderJPanel", new RequestTransferJPanel(userProcessContainer, account, foodBank, business, government));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiveActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "please select a row");
            return;
        }
        FoodRequest request = (FoodRequest) workRequestJTable.getValueAt(selectedRow, 0);
        request.setStatus("Completed");
        FoodInventory in = new FoodInventory();
        in.setFood(request.getFood());
        in.setQuantity(request.getQuantity());
        if (foodBank.searchInventory(in.getFood()) == null) {
            foodBank.addInventory(in);
        } else {
            int addNum = request.getQuantity();
            int oldNum = foodBank.searchInventory(in.getFood()).getQuantity();
            foodBank.searchInventory(in.getFood()).setQuantity(addNum + oldNum);
        }
        populateFoodBankInventoryTable();
        populateFoodBankTransferRequestTable();
    }//GEN-LAST:event_btnReceiveActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "please select a row");
            return;
        }

        FoodRequest request = (FoodRequest) workRequestJTable.getValueAt(selectedRow, 0);

        if (foodBank.searchInventory(request.getFood()) == null) {
            JOptionPane.showMessageDialog(null, "there is no such food");
            return;
        } else {
            int oldNum = foodBank.searchInventory(request.getFood()).getQuantity();
            if (oldNum - request.getQuantity() < 0) {
                JOptionPane.showMessageDialog(null, "lack stock");
                return;
            } else {
                foodBank.searchInventory(request.getFood()).setQuantity(oldNum - request.getQuantity());
                request.setReceiver(account);
                request.setStatus("Pending");
            }
        }

        populateFoodBankInventoryTable();
        populateFoodBankTransferRequestTable();
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnShippingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShippingActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "please select a row");
            return;
        }
        FoodRequest request = (FoodRequest) workRequestJTable.getValueAt(selectedRow, 0);
        if (!request.getStatus().equals("Pending")) {
            JOptionPane.showMessageDialog(null, "please assign this request first");
            return;
        }
        request.setStatus("Processing");

        ProcessTransJPanel processTransJPanel = new ProcessTransJPanel(userProcessContainer, request);
        userProcessContainer.add("ProcessTransJPanel", processTransJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnShippingActionPerformed

    private void workRequestJTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_workRequestJTablePropertyChange

    }//GEN-LAST:event_workRequestJTablePropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReceive;
    private javax.swing.JButton btnRequest;
    private javax.swing.JButton btnShipping;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblin;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
